# Generated by Django 5.2.5 on 2025-08-21 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_record_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='Category',
            new_name='category',
        ),
    ]
